<a href="https://colab.research.google.com/github/19pa1a0268/-AI--Lab-/blob/master/Experiment%201%20numpy%20ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#experiment-1 Numpy

##Different ways to create numpy arrays

In [3]:
import numpy as np
a=np.array([4,5,6])
print(a)

[4 5 6]


In [4]:
a=np.array([[4,5],[6,7]])
print(a)

[[4 5]
 [6 7]]


##Add,remove,modify elements in an array

In [5]:
newArray=np.append(a,[66,71,45])
print(newArray)

[ 4  5  6  7 66 71 45]


In [6]:
import numpy as np
l=np.array([5,6,3,9,8])
l=np.delete(l,4)
print(l)

[5 6 3 9]


In [8]:
b=np.array([6,4,5,9,2,1])
b[b<2]=-1
print(b)

[ 6  4  5  9  2 -1]


##arthametic operations on numpy arrays

In [11]:
import numpy as np
k=np.random.random((4,4))
v=np.random.random((4,4))
sum=np.add(k,v)
diff=np.subtract(k,v)
prod=np.multiply(k,v)
quo=np.divide(k,v)
mod=np.mod(k,v)
Pow=np.power(k,v)
print(sum)
print(diff)
print(prod)
print(quo)
print(mod)
print(pow)

[[1.27003422 0.45708715 0.90982189 0.91700912]
 [1.05250303 0.37188718 1.25281516 1.6347615 ]
 [1.68375134 0.70884459 0.56676525 0.18855292]
 [1.58484732 1.56827911 1.26959424 1.09392006]]
[[-0.43594022  0.30225426  0.22762676  0.29099352]
 [-0.33413127  0.04265303  0.04393034 -0.02950113]
 [ 0.29211652  0.54899654  0.33204403 -0.14477482]
 [ 0.17929042 -0.27288609 -0.33082219  0.37574917]]
[[0.35573576 0.02939276 0.19399048 0.18905713]
 [0.24902973 0.0341202  0.39190399 0.66789371]
 [0.68742163 0.05026586 0.0527424  0.00364811]
 [0.619899   0.59625814 0.37560655 0.26386841]]
[[0.48892527 4.9042642  1.66733622 1.92966857]
 [0.51806865 1.2591045  1.07267911 0.96454751]
 [1.41981778 7.86898022 3.82926303 0.13133649]
 [1.25511656 0.7035724  0.58657987 2.04640603]]
[[0.417047   0.07000492 0.22762676 0.29099352]
 [0.35918588 0.04265303 0.04393034 0.80263019]
 [0.29211652 0.0694524  0.09732281 0.02188905]
 [0.17929042 0.64769651 0.46938603 0.01666373]]
<built-in function pow>


##slicing, iterating of numpy arrays

#slicing

In [12]:
import numpy as np
arr=np.array([4,3,2,1,6,7])
print(a[2:6])

[]


#iterating

In [14]:
for i in arr:
  print(i)

4
3
2
1
6
7


##matrix Operations on numpy arrays

In [16]:
import numpy as np
u=np.array([[5,9],[4,3]])
k=np.array([[2,16],[1,12]])
print(np.add(u,k))
print(np.subtract(u,k))
print(np.divide(u,k))

[[ 7 25]
 [ 5 15]]
[[ 3 -7]
 [ 3 -9]]
[[2.5    0.5625]
 [4.     0.25  ]]
