<a href="https://colab.research.google.com/github/19pa1a0268/-AI--Lab-/blob/master/Experiement-1-numpy-ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 Experiment 1 Numpy 1.Different ways to create numpy array

In [3]:
 
 
import numpy as np
a = np.array([1,4,6])
print(a)

[1 4 6]


In [4]:
 
 
a=np.array([[1,9], [2,7]])
print(a)

[[1 9]
 [2 7]]


 2.Add,remove,modify elements in an array

In [5]:
 
 
newArray = np.append(a,[11,44,56])
print(newArray)

[ 1  9  2  7 11 44 56]


In [6]:
 
import numpy as array
l=np.array([4,6,9,3,7])
l=np.delete(l,2)
print(l)

[4 6 3 7]


In [7]:
 
b=np.array([1,7,4,3,2,5])
b[b<2]=-1
print(b)

[-1  7  4  3  2  5]


 3.Arthematic operations on numpy array

In [9]:
 
 
import numpy as np
k=np.random.random((2,2))
v=np.random.random((2,2))
sum=np.add(k,v)
diff=np.subtract(k,v)
prod=np.multiply(k,v)
quo=np.divide(k,v)
mod=np.mod(k,v)
pow=np.power(k,v)
print(sum)
print(diff)
print(prod)
print(quo)
print(mod)
print(pow)

[[1.00277158 0.70465428]
 [0.60027864 0.38045652]]
[[ 0.82441156  0.38698303]
 [ 0.0190861  -0.01558388]]
[[0.08147411 0.08669545]
 [0.08999254 0.03612608]]
[[10.24435367  3.43637423]
 [ 1.06567911  0.92130155]]
[[0.02179146 0.06931177]
 [0.0190861  0.18243632]]
[[0.99197304 0.90830962]
 [0.71131543 0.71397846]]


 4.Slicing and iterating of numpy arrays
 
 
 Slicing

In [10]:
 
 
import numpy as np
arr=np.array([4,2,5,6,7,8])
print(arr[2:6])

[5 6 7 8]


Iterating

In [12]:
 
for i in arr:
  print(i)

4
2
5
6
7
8


 5.Matrix operations on numpy arrays

In [13]:
 
import numpy as np
k=np.array([[1,2],[4,5]])
v=np.array([[9,11],[7,17]])
print(np.add(k,v))
print(np.subtract(k,v))
print(np.divide(k,v))

[[10 13]
 [11 22]]
[[ -8  -9]
 [ -3 -12]]
[[0.11111111 0.18181818]
 [0.57142857 0.29411765]]
