<a href="https://colab.research.google.com/github/19pa1a0268/-AI--Lab-/blob/master/Experiment-1-numpy-ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment-1 Numpy
##Different ways to create numpy arrays

In [ ]:
 
import numpy as np
a = np.array([1,4,6])
print(a)

[1 4 6]


In [ ]:
 
a=np.array([[1,9], [2,7]])
print(a)

[[1 9]
 [2 7]]


##Add,remove,modify elements in an array

In [ ]:
 
newArray = np.append(a,[11,44,56])
print(newArray)

[ 1  9  2  7 11 44 56]


In [ ]:
 
import numpy as array
l=np.array([4,6,9,3,7])
l=np.delete(l,2)
print(l)

[4 6 3 7]


In [ ]:
 
b=np.array([1,7,4,3,2,5])
b[b<2]=-1
print(b)

[-1  7  4  3  2  5]


##Arthametic operations on numpy array

In [ ]:
 
import numpy as np
k=np.random.random((2,2))
v=np.random.random((2,2))
sum=np.add(k,v)
diff=np.subtract(k,v)
prod=np.multiply(k,v)
quo=np.divide(k,v)
mod=np.mod(k,v)
pow=np.power(k,v)
print(sum)
print(diff)
print(prod)
print(quo)
print(mod)
print(pow)

[[1.66826603 1.64871931]
 [0.79293604 1.50647538]]
[[-0.02608722 -0.10451433]
 [ 0.67024391 -0.45849653]]
[[0.69560775 0.67683803]
 [0.04488017 0.51481225]]
[[ 0.96920687  0.88077535]
 [11.9256219   0.53333019]]
[[0.82108941 0.77210249]
 [0.05678326 0.52398942]]
[[0.84620111 0.79713885]
 [0.98100983 0.52995417]]


##slicing and iterating on numpy arrays



##slicing

In [ ]:
 
import numpy as np
arr=np.array([4,2,5,6,7,8])
print(arr[2:6])

[5 6 7 8]


##iterating

In [ ]:
 
for i in arr:
  print(i)

4
2
5
6
7
8


##Matrix operations on numpy arrays

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [1]:
 
import numpy as np
k=np.array([[1,2],[4,5]])
v=np.array([[9,11],[7,17]])
print(np.add(k,v))
print(np.subtract(k,v))
print(np.divide(k,v))

[[10 13]
 [11 22]]
[[ -8  -9]
 [ -3 -12]]
[[0.11111111 0.18181818]
 [0.57142857 0.29411765]]
